#!/usr/bin/env python3

from ev3dev2.sensor import Sensor, INPUT_1, INPUT_2, INPUT_3, INPUT_4
from ev3dev2.sensor.lego import ColorSensor, UltrasonicSensor
from ev3sim.code_helpers import wait_for_tick
from ev3dev2.motor import MoveTank, OUTPUT_B, OUTPUT_C
from ev3dev2.display import Display
from time import sleep

# Initialise the display, colour sensors and motors
display = Display()
cl_1 = ColorSensor(INPUT_4)
ultrasonic = UltrasonicSensor(INPUT_3)
distance = ultrasonic.distance_centimeters
# cl_3 = ColorSensor(INPUT_3)
cl_4 = ColorSensor(INPUT_1)
motors = MoveTank(OUTPUT_B, OUTPUT_C)

# INPUT_4 is the right colour sensor, INPUT_1 is left
cl_1.mode = ColorSensor.MODE_COL_COLOR
cl_4.mode = ColorSensor.MODE_COL_COLOR



def followLine():
    detectable_colours = [ColorSensor.COLOR_BLACK, ColorSensor.COLOR_GREEN, ColorSensor.COLOR_RED]
#     # the direction variable gets returned by this function which will determine which
#     # way the robot goes based on the colour sensors.
    direction = ""
    if cl_1.color == ColorSensor.COLOR_BLACK:
        direction = "right"
    if cl_4.color == ColorSensor.COLOR_BLACK:
        direction = "left"
    if cl_1.color == ColorSensor.COLOR_BLACK and cl_4.color == ColorSensor.COLOR_BLACK:
        # direction = green_intersection_direction
        direction = "forward"
    # if cl_1.color not in detectable_colours and cl_4.color not in detectable_colours:
    #     direction = "forward"
    if cl_1.color != ColorSensor.COLOR_BLACK and cl_4.color != ColorSensor.COLOR_BLACK:
        direction = "forward"

    return direction

while True:
    direction = followLine() # set followLine() to a variable so it can be used in the if statements below
    if direction == "right":
        # When the right colour sensor detects black, the robot will turn right to follow the line
        motors.on(left_speed=-5, right_speed=0)
    elif direction == "left":
        # Same as above but for the left colour sensor
        motors.on(left_speed=0, right_speed=-5)
    elif direction == "forward":
        # Move forward when both colour sensors are not detecting black
        motors.on(left_speed=-5, right_speed=-5)